<template>
  <!--账单管理-->
<init :default-clear="false">
  billList,
  billListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillListbillList
  <input v-model="vv">

</init>
</template>

<script>
export default {
  name: "billList",
  data(){
    return{
      vv:''
    }
  }
}
</script>

<style scoped>

</style>